services:
  - type: web
    name: flask-audio-tattoo
    env: python
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
